# Generated by Django 5.2.7 on 2026-03-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('NGO', 'Ngo'), ('RESTAURANT', 'Restaurant')], default='NGO', max_length=20),
        ),
    ]
