# Generated by Django 5.2.7 on 2026-03-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_otp_created_at_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
