# Generated by Django 5.2.7 on 2025-10-22 13:21

import apps.ticket.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NGO', '0001_initial'),
        ('restaurant', '0002_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Human', 'Human'), ('Animal', 'Animal')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ticket_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(default=apps.ticket.models.expired_time)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_tickets', to='NGO.ngo')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
