"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x-+ju##aif2wy_nv-j@a=^*x=#51ix!)cvjkde32@0xhqx5zyw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    #apps
    'apps.account',
    'apps.donations',
    'apps.NGO',
    'apps.Restaurant',
    'apps.notification',
    
    
    # service
    
    'channels',
    'django_celery_beat',
   
    
    #corss header
    'corsheaders',
    
    #db
    'django.contrib.gis',
    
    'phonenumber_field',

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
load_dotenv()
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv("DB_NAME"),
        'USER' : os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
       
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        ],
    'DEFAULT_THROTTLE_CLASSES':[
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "apps.account.function.RateLimit.RateLimit",
    ],
    "DEFAULT_THROTTLE_RATES":{
        "anon":"10/minute",
        "user":"20/minute",
        "otp" : "3/minute"
    }
}





# firebase 
import firebase_admin
from firebase_admin import credentials

cred = credentials.Certificate("backend/serviceAccountKey.json")
firebase_admin.initialize_app(cred)




#cross_headers
CORS_ALLOW_ALL_ORIGINS = True



import os

GDAL_LIBRARY_PATH = r"C:\Users\BPW\AppData\Local\Programs\OSGeo4W\bin\gdal312.dll"
GEOS_LIBRARY_PATH = r"C:\Users\BPW\AppData\Local\Programs\OSGeo4W\bin\geos_c.dll"






AUTH_USER_MODEL = 'account.User'


# JWT

from datetime import timedelta

SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME":
    timedelta(days=1),
        "REFRESH_TOKEN_LIFETIME":
    timedelta(days=7),
        "AUTH_HEADER_TYPES":("Bearer",),
}


# sms

FAST2SMS_API_KEY = os.getenv("API_KEY")


#redis (celery broker)

CELERY_BROKER_URL = os.getenv("REDIS")
CELERY_ACCEPT_CONTENT= ["json"]
CELERY_TASK_SERIALIZER = "json"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1", 
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",}}}



#celery-beat

CELERY_BEAT_SCHEDULE = {
    "check-donation-every-1-min":{
        "task":"apps.donations.tasks.check_and_update_donations",
        "schedule":60.0,
    },
}


ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYER ={
    "default":{
        "BACKEND":"channels_redis.core.RedisChannelLayer",
        "CONFIG":{
            "hosts":[("127.0.0.1",6379)],
        },
    },
}