# Generated by Django 5.2.7 on 2025-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('NGO_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], default='Private', max_length=10)),
            ],
        ),
    ]
