# Generated by Django 5.2.7 on 2025-10-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_ngo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
