# Generated by Django 5.2.7 on 2026-03-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NGO', '0002_initial'),
        ('Restaurant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PICKED_UP', 'Pick up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('food_type', models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non veg')], max_length=20)),
                ('food_description', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('pickup_time', models.DateTimeField()),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('search_radius', models.IntegerField(default=15)),
                ('radius_increment', models.IntegerField(default=5)),
                ('max_radius', models.IntegerField(default=50)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accept_donation', to='NGO.ngoprofile')),
                ('donated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='Restaurant.restaurantprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='donations_d_status_73ca83_idx'), models.Index(fields=['created_at'], name='donations_d_created_26bd74_idx'), models.Index(fields=['search_radius'], name='donations_d_search__72bebe_idx'), models.Index(fields=['expiry_time'], name='donations_d_expiry__6ac6cf_idx')],
            },
        ),
    ]
